### PR TITLE
Use CMake variable for dl library

### PR DESCRIPTION
**Pull request by flagarde**
Hi, CMake provide a variable for `dl` library as it seems the name can change depending on some system. https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html

I think using the variable the library can be linked unconditionally

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Thanks! Looks good to me

**Comment by jeremy-rifkin** [comment]
I’ll apply this change to the dev branch too

**Comment by flagarde** [comment]
sorry I have not seen the dev branch 😬

**Comment by jeremy-rifkin** [comment]
All good! It might be good to add something to the readme about its existence.

**Pull request merged**
