### PR TITLE
Add 'POSITION_INDEPENDENT_CODE ON' (also known as '-fPIE').

### PR DESCRIPTION
**Pull request by kouchy**
First thx for these very useful lib!

I encountered some issues when linking with `libcpptrace`. Typically, here is the error I got:
```
/usr/bin/ld: lib/cpptrace/lib/libcpptrace.a(cpptrace.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE@@GLIBCXX_3.4.21' can not be used when making a PIE object; recompile with -fPIE
```
I just added the `POSITION_INDEPENDENT_CODE ON` flag on the targets, and now it works like a charm :-).

### CODE REVIEW

**Comment by jeremy-rifkin** [comment]
Hey thanks for the PR! I think looks good to me but let me double check the implications later today. It might be desirable to have an option for whether or not to use PIC.

**Comment by kouchy** [comment]
Fair enough, sounds wise :-).

**Comment by kouchy** [comment]
I updated my PR :-)

**Comment by jeremy-rifkin** [comment]
Awesome thank you so much!

**Review by jeremy-rifkin — APPROVED** [review]

**Pull request merged**
